### PR TITLE
fix(checkout): CHECKOUT-6860 Use numeric keypad to type phone number

### PR DESCRIPTION
**Pull request by bc-peng**
## What?
Using a numeric keypad to enter tel numbers.

## Why?
Speed up the checkout.

## Testing / Proof

@bigcommerce/checkout

### CODE REVIEW

**Comment by icatalina** [comment]
Number is not a good keyboard for telephone, can we get something like `type="tel"` instead?

**Comment by bc-peng** [comment]
> Number is not a good keyboard for telephone, can we get something like `type="tel"` instead?

@icatalina  We do use `type="tel"`, the final html code on the shipping form is:
```
<input aria-labelledby="phoneInput-label phoneInput-field-error-message" autocomplete="tel" id="phoneInput" name="shippingAddress.phone" class="form-input optimizedCheckout-form-input" type="tel" data-test="phoneInput-text" value="">
```

**Comment by icatalina** [comment]
Why is it showing the `,` and `.` then? I'd expect the `tel` type to look a bit more like this: 

IMAGE 2022-09-13 12:48:25

**Comment by icatalina** [comment]
Is that an emulator thing? 🤔

**Comment by bc-peng** [comment]
> Is that an emulator thing? 🤔

It turns out the kepad in the description is a custom form field with `type="number"`, the telephone number's keypad in the shipping looks like this on my Pixel. I have updated the description. Thanks for the catch.

**Review by animesh1987 — APPROVED** [review]

**Pull request merged**
