### PR TITLE
refactor(payment): INT-1866 Update Visa Checkout to Visa SRC

### PR DESCRIPTION
**Pull request by mauricio-sg**
## What? [INT-1866](https://jira.bigcommerce.com/browse/INT-1866)

1. Replace the `Visa Checkout` text with `Click to pay`.
2. Show the logo and name aside.

## Why?
As part of the transition to Visa SRC.

## Testing / Proof
_Before:_
before
_Now:_
now

## Sibling PR
👉 https://github.com/bigcommerce/bigcommerce/pull/44010

@bigcommerce/apex-integrations @bigcommerce/checkout

### CODE REVIEW

**Review by JoseAlvarezHdz — APPROVED** [review]
LGTM 👍🏾

**Comment by TomA-R** [comment]
I know this is the requirement in the ticket but it seems a bit weird to me. Visa's examples [[consumer](https://www.visa.com.au/pay-with-visa/checkout.html), [merchant](https://www.visa.com.au/run-your-business/small-business-tools/payment-technology/checkout.html)] make a lot more sense to me. Unless there's a lot of brand awareness of the term "Click to Pay" (across different countries), I'd say sentences like "Doorgaan met Click to pay" seem like an unusual experience for shoppers. I _imagine_ Visa's desires are to just replace the "VISA Checkout" logo with the squiggly line, like here:



No blocker if we're sure this is the desired new look. cc @knowakowski @bc-erich

**Comment by knowakowski** [comment]
> I know this is the requirement in the ticket but it seems a bit weird to me. Visa's examples [[consumer](https://www.visa.com.au/pay-with-visa/checkout.html), [merchant](https://www.visa.com.au/run-your-business/small-business-tools/payment-technology/checkout.html)] make a lot more sense to me. Unless there's a lot of brand awareness of the term "Click to Pay" (across different countries), I'd say sentences like "Doorgaan met Click to pay" seem like an unusual experience for shoppers. I _imagine_ Visa's desires are to just replace the "VISA Checkout" logo with the squiggly line, like here:
> 
> 
> 
> No blocker if we're sure this is the desired new look. cc @knowakowski @bc-erich

@TomA-R That button is what shows on the cart, quick cart and Customer section of checkout.
However, for the Payment section, Visa has a different requirement which is #1 boxed in red here:
Screen Shot 2021-12-03 at 11 12 29 AM

the problem is that when we implemented that, it made the alignment look off:
Screen Shot 2021-12-03 at 11 14 25 AM

So, we decided to go with #2 here instead:

Screen Shot 2021-12-03 at 11 12 29 AM

**Comment by BC-AAcevedo** [comment]
:green_heart: tested
QA Details: Logo showing as expected on checkout page

**Review by TomA-R — APPROVED** [review]
Thanks for the explanation, @knowakowski! No objections from me then. It still seems quite strange to have an unknown squiggly line (at least I don't recognise it) and "Click to pay" as a payment option in e.g. Dutch. You don't pay when you click it (it just selects the option), and it's in English

**Review by animesh1987 — APPROVED** [review]

**Pull request merged**
