### PR TITLE
feat(checkout): CHECKOUT-0000 Merge prettier auto fixes

### PR DESCRIPTION
**Pull request by bc-peng**
## What?
Automatic code formatting improvement by `prettier`.

## Why?
These auto fixes constantly show up when we run `npm run lint` because we never commit them into the repo.

## Testing / Proof
CI.

@bigcommerce/checkout

### CODE REVIEW

**Review by davidchin — APPROVED** [review]
LGTM. Separate question, why aren't these raised as an error in the first place?

**Comment by bc-peng** [comment]
> LGTM. Separate question, why aren't these raised as an error in the first place?

@davidchin I think because they are all auto-fixable, and we run `npm run lint` with `--fix`.

**Comment by davidchin** [comment]
@bc-peng we should put in something to fail the build if the autofix changes are not committed. This is to prevent similar things from happening again in the future.

**Comment by animesh1987** [comment]
@bc-peng correct me if I am wrong, these are fixes that are suggested but we haven't actioned on till now. Since most of the rules are turned off in core repo it could be a reason why the build doesn't fail.

**Comment by bc-peng** [comment]
> @bc-peng we should put in something to fail the build if the autofix changes are not committed. This is to prevent similar things from happening again in the future.

@davidchin as we will commit all auto fixes in this PR, maybe we can remove `--fix` from now on.
https://github.com/bigcommerce/checkout-js/blob/d8a6c79870877788bf21ca6ef6bc9e25a56c7df3/package.json#L23

**Comment by bc-peng** [comment]
> @bc-peng correct me if I am wrong, these are fixes that are suggested but we haven't actioned on till now. Since most of the rules are turned off in core repo it could be a reason why the build doesn't fail.

@animesh1987 Some of them are errors, some are warnings.
If we run `npx nx run-many --target=lint --all` without `--fix` on master branch now, the command will fail.

**Pull request merged**
