### PR TITLE
fix(checkout): ADYEN-38 Fix Adyen icons on checkout page

### PR DESCRIPTION
**Pull request by vneutrino**
## What?
Made logos for Klarna methods on checkout consistent.

## Why?
According to task https://jira.bigcommerce.com/browse/ADYEN-38
Logos for Klarna methods on checkout seem inconsistent. 

#### BEFORE:
image

### AFTER:
image

@bigcommerce/checkout

### CODE REVIEW

**Review by BC-ACherednichenko — APPROVED** [review]
Nicely done!

**Review by davidchin — COMMENTED** [review]
Why don't you just fix the image itself instead of changing the code (i.e.: point to a different image other than `/img/payment-providers/klarna-header.png`)?

**Comment by vneutrino** [comment]
@davidchin because AdyenV2 payment methods icons have smaller size than icons from our CDN.
If I change Klarna icon at our CDN, we will have inconsistency in icons with another payment gateway.
That's why I've changed an order in title selection, the `method.gateway` has a higher priority than `method.id`.

**Comment by davidchin** [comment]
I'm not entirely sure why Adyen has anything to do with Klarna 🤔

**Comment by vneutrino** [comment]
@davidchin Adyen provides Klarna as payment method for EU countries

**Review by davidchin — APPROVED** [review]

**Pull request merged**
